language: python
python:
  - "3.7"
install:
  - pip install git+https://github.com/hasgeek/flask-babelhg/
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - ./runtests.sh
after_success:
  - coveralls
notifications:
  email: false
  slack:
    - hasgeek:HDCoMDj3T4ICB59qFFVorCG8
    - friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
